### ISSUE TITLE
Update the URL of LTileLayer

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-leaflet#4]
After createing a `LTileLayer` you cannot update the URL of the tile source. This is pretty critical. The following does not seem to work

```py
layer = = LTileLayer(url='/{z}/{x}/{y}.png?filename=foo')

...

layer.url = '/{z}/{x}/{y}.png?filename=bar'
```

**Comment by jourdain** [comment]
Expected as it is not the way to handle dynamic parameters in trame. You probably have the trait logic of Jupyter that is playing against you here.

To do it in trame:

```python
LTileLayer(
  url=(layer_url, '/{z}/{x}/{y}.png?filename=foo'),
)

...

state.layer_url = '/{z}/{x}/{y}.png?filename=bar'
```

**Comment by jourdain** [comment]
Anything you do on a widget is static and final unless you flush the layout again...

**Comment by banesullivan** [comment]
This is a pretty critical issue. Can we remove the old tile layer and add a new one?

**Comment by banesullivan** [comment]
Ah right, us a JS variable, got it, thanks

**Comment by jourdain** [comment]
I would not call it a JS variable but a `shared state variable` instead as it is available on both side...
