### ISSUE TITLE
LTileLayer is missing parameters

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-leaflet#5]
See https://leafletjs.com/reference.html#tilelayer for the full API to leafelt's tile layer

It appears to me that `minZoom` and `maxZoom` are missing from this wrapping:

https://github.com/Kitware/trame-leaflet/blob/56baace466fd5c2851e0b8cddcb6bc8adab2ca91/trame_leaflet/widgets/leaflet.py#L410-L429

**Comment by jourdain** [comment]
Looking at the wrong doc: https://vue2-leaflet.netlify.app/components/LTileLayer.html#props

**Comment by banesullivan** [comment]
Ah thanks. I looks like `maxZoom` are only exposed on the `LMap` in vue-leaflet... which might be transferred to the TileLayer. I'll have to look into this further later
