### ISSUE TITLE
Dropdown menu overlapped by tile layer

### ISSUE THREAD

**Issue by cardinalgeo** [Kitware/trame-leaflet#6]
Hi Trame Team! 

How do I ensure that the dropdown options are in front of the tile layer rather than behind, as they currently are in the screenshot below? 

![Screen Shot 2023-02-09 at 6 53 43 PM](https://user-images.githubusercontent.com/44422832/217966286-d6280e97-565e-4469-9068-1eff35a0554b.png)

**Comment by jourdain** [comment]
@banesullivan just solved it on his testing by bumping the z-index.

**Comment by jourdain** [comment]
Not sure about the exact fix but I think he did the following

```python
with layout.toolbar as toolbar:
   toolbar.style = "z-index: 1000"
```

**Comment by cardinalgeo** [comment]
Yes, I talked with Bane about it recently! Hmm, I've changed the value passed to `zIndex` without any success.

For example: 
```
with leaflet.LMap(zoom=("zoom", 1)):
    # tiles
    image_viewer = leaflet.LTileLayer(url=("tile_url", "/tile/{z}/{x}/{y}.png"), zIndex=10)
```

Should I be approaching this a different way? I can provide a full minimum reproducible example if that'd be of use!

**Comment by cardinalgeo** [comment]
Ah your most recent message just came in — I'll give it a try

**Comment by cardinalgeo** [comment]
This worked, thanks @jourdain  and @banesullivan!

**Comment by banesullivan** [comment]
@cardinalgeo, take a look at my Trame-tileserver example for some updates to the problems you had

**Comment by cardinalgeo** [comment]
Ooh, I'll take a look!

**Comment by banesullivan** [comment]
We should re-open this issue as it appears that the issue is with the `z-index` of the TileLayer. The `zIndex` prop of the `LTileLayer` doesn't seem to be used:

```py
from trame.app import get_server
from trame.ui.vuetify import SinglePageLayout
from trame.widgets import leaflet, vuetify

server = get_server()
state, ctrl = server.state, server.controller

state.trame__title = "Leaflet Test"


with SinglePageLayout(server) as layout:
    # Toolbar
    layout.title.set_text(state.trame__title)

    with layout.toolbar:
        layout.toolbar.style = "z-index: 2;"

        vuetify.VSpacer()

        vuetify.VSelect(
            v_model=("table_name", "table 1"),
            items=("table_names", ["table 1", "table 2"]),
            dense=True,
            hide_details=True,
            style="max-width: 200px;",
        )

    # Main content
    with layout.content:
        with vuetify.VContainer(fluid=True, classes="pa-0 fill-height"):
            with leaflet.LMap(zoom=3):
                leaflet.LTileLayer(
                    url=(
                        "basemap_url",
                        "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                    ),
                    attribution=(
                        "attribution",
                        '&copy; <a target="_blank" href="http://osm.org/copyright">OpenStreetMap</a> contributors',
                    ),
                    z_index=1,
                )

    # Footer
    layout.footer.hide()


if __name__ == "__main__":
    server.start()
```

<img width="1756" alt="Screen Shot 2023-04-26 at 9 29 58 AM" src="https://user-images.githubusercontent.com/22067021/234625623-b8d5085a-878a-435b-8494-938267127304.png">

**Comment by jourdain** [comment]
That a style thing, not an attribute?

**Comment by banesullivan** [comment]
We should be able to control it via this attribute, right?

https://github.com/Kitware/trame-leaflet/blob/c4ea0a2ef76986033f8e114076058df9c25209e4/trame_leaflet/widgets/leaflet.py#L446

**Comment by jourdain** [comment]
If that list of attributes are correct, then yes. But that could also be
internal to the layers and not css related. You may need to adjust the
zindex of the main map container using the style if you want the drop down
to go above.

**Comment by banesullivan** [comment]
Following up from offline conversations. This needs to be done with styling and the `z_index` property is for managing relative z levels of layers/markers in leaflet (as far as I can tell).

When creating the `LMap`, style it like:

```py
with leaflet.LMap(style="z-index: 0;"):
    ...
```
