### ISSUE TITLE
Removing doubled-up tiles

### ISSUE THREAD

**Issue by cardinalgeo** [Kitware/trame-leaflet#8]
Hello! 

As you can see in the example video below, at least three images are stacked on top of each other (note image to the right and image peeking out at the bottom) when I expect only one image to be present. Do you have any suggestions on how to remove the two back images? I can't seem to identify a parameter in either `leaflet.LMap` or `leaflet.LTileLayer` that will resolve this. 

https://user-images.githubusercontent.com/44422832/218005796-c4b595f4-69ef-4c14-bc60-aed290b200e3.mov

**Comment by jourdain** [comment]
We probably need some code to see what you are doing.

**Comment by jourdain** [comment]
Did you print the layout HTML to make sure you did not create 3 `LMap` based on the way you defined your UI in Python?

**Comment by cardinalgeo** [comment]
I've seen no evidence of 3 or more `LMap` objects in the html, though I must admit I'm not experienced on the html side of things. Another thought is that somehow tiles at different zoom levels are being displayed simultaneously? 
Here is a minimum reproducible example: 
```python
"""Image tile serving with large-image and trame."""

import io
import json

import large_image
from aiohttp import web
from trame.app import get_server
from trame.ui.vuetify import SinglePageWithDrawerLayout
from trame.widgets import leaflet, vuetify


server = get_server()
state, ctrl = server.state, server.controller
 
image = "/Users/robertcollar/Documents/CACB_Field_Work_2022/sample_photos/test/pyramids/IMG_1531.tiff"

# Open raster with large-image
class image_handler(): 
    def __init__(self, image): 
        self.open_image(image)
    def open_image(self, image): 
        self.src = large_image.open(
            image,
            encoding="PNG",
        )
    async def metadata(self, request):
        """REST endpoint to get image metadata."""
        return web.json_response(self.src.getMetadata())

    async def tile(self, request):
        """REST endpoint to server tiles from image in slippy maps standard."""
        z = int(request.match_info["z"])
        x = int(request.match_info["x"])
        y = int(request.match_info["y"])
        tile_binary = self.src.getTile(x, y, z)
        return web.Response(body=io.BytesIO(tile_binary), content_type="image/png")


handler= image_handler(image)

my_routes = [web.get("/metadata", handler.metadata), web.get("/tile/{z}/{x}/{y}.png", handler.tile)]

@server.controller.add("on_server_bind")
def app_available(wslink_server):
    """Add our custom REST endpoints to the trame server."""
    wslink_server.app.add_routes(my_routes)


# -----------------------------------------------------------------------------
# UI
# -----------------------------------------------------------------------------


with SinglePageWithDrawerLayout(server) as layout:
    layout.title.set_text("Large Image Trame Web App")

    with layout.toolbar as toolbar:
        toolbar.style = "z-index: 1000"
        vuetify.VSpacer()

        vuetify.VSwitch(
            hide_details=True,
            v_model=("$vuetify.theme.dark",),
        )
        vuetify.VProgressLinear(
            indeterminate=True,
            absolute=True,
            bottom=True,
            active=("trame__busy",),
        )

    with layout.content:
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            with leaflet.LMap(zoom=("zoom", 1), maxZoom=15):
                # tiles
                image_viewer = leaflet.LTileLayer(url="/tile/{z}/{x}/{y}.png", noWrap=True, maxZoom=15)

if __name__ == "__main__":
    server.start(port=8080)
```

**Comment by jourdain** [comment]
Indeed I don't see anything wrong at first glance... 
Not sure if the issue is coming from the [vue2-leaflet](https://vue2-leaflet.netlify.app/components/LTileLayer.html#props) library we are exposing...

**Comment by cardinalgeo** [comment]
Got it – what would you suggest I do to diagnose this issue?

**Comment by jourdain** [comment]
Not sure but since we would need a deeper investigation, we may have to rely on some funding source (which you may already have with Bane?)

**Comment by cardinalgeo** [comment]
Hi @jourdain, unfortunately there is no funding agreement between us! Simply an open source enthusiast trying to understand (and hopefully overcome) the barriers to building useful tools (in my case for a graduate research project!).

**Comment by jourdain** [comment]
No worries and hopefully we'll manage to figure it out.

**Comment by cardinalgeo** [comment]
Hey team! Quick update — resolved the doubled-up tiles issue. To summarize, when an image cannot be broken up into equidimensional tiles, the `large_image` `edge` style parameter — documented [here](https://girder.github.io/large_image/tilesource_options.html#edges) – determines how the excess space beyond the image's edge is filled. Setting that parameter to `"#DDDDDD"` fills the excess space with the same default color as the `trame-leaflet` background (see example below)! 

<img width="608" alt="Screen Shot 2023-03-11 at 11 59 28 AM" src="https://user-images.githubusercontent.com/44422832/224499456-ca957bb7-0055-4162-bdb1-7ed45c21e494.png">
